services:
  tts-service:
    container_name: tts-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
#    volumes:
#      - /root/www:/app/html  # 如果不需要 html/，可以移除此行
#    environment:
#      - TOKEN=${TOKEN} # 可选
    restart: unless-stopped
